PermissionManagerService: Correct don't enforce privapp perms for updated system apps
Issue:

java.lang.IllegalStateException: Signature|privileged permissions not in privapp-permissions whitelist: {com.google.android.projection.gearhead (/data/app/~~WSwlGmikwcVQrwQDXwWdAA==/com.google.android.projection.gearhead-bzzvY3HIOB9kXhNRPB2AfA==)}

Somehow pkgSetting.getPkgState().isUpdatedSystemApp() is returning false, so device enters into bootloop state due to that bad behavior.

Change-Id: I1e9fb1175473e8c8ec1e5e3c519947d3414c57ee